Repository OCA/commission, pull requests merged in 2018-11, with the labels that each got.

#184 [10.0] FIX sale_commission_areamanager: better inheritance of partner view
  sale_commission_areamanager/__manifest__.py
  sale_commission_areamanager/views/res_partner_view.xml
Labels: needs review

#183 ADD sale_commission_geo_assign
  sale_commission_geo_assign/README.rst
  sale_commission_geo_assign/__init__.py
  sale_commission_geo_assign/__manifest__.py
  sale_commission_geo_assign/models/__init__.py
  sale_commission_geo_assign/models/res_partner.py
  sale_commission_geo_assign/readme/CONFIGURE.rst
  sale_commission_geo_assign/readme/DESCRIPTION.rst
  sale_commission_geo_assign/readme/USAGE.rst
  sale_commission_geo_assign/static/description/index.html
  sale_commission_geo_assign/tests/__init__.py
  sale_commission_geo_assign/tests/test_sale_commission_geo_assign.py
  sale_commission_geo_assign/views/res_partner_view.xml
  sale_commission_geo_assign/wizard/__init__.py
  sale_commission_geo_assign/wizard/wizard_geo_assign_partner.py
  sale_commission_geo_assign/wizard/wizard_geo_assign_partner_view.xml
Labels: approved, needs review, ready to merge

#189 [IMP] Add hook on the create settlements
  sale_commission/__manifest__.py
  sale_commission/models/account_invoice.py
  sale_commission/wizard/wizard_settle.py
Labels: approved

#151 [FIX] sale_commission: Avoid erasing of invoice agents
  sale_commission/README.rst
  sale_commission/__manifest__.py
  sale_commission/i18n/es.po
  sale_commission/models/__init__.py
  sale_commission/models/account_invoice.py
  sale_commission/models/sale_commission_mixin.py
  sale_commission/models/sale_order.py
  sale_commission/models/settlement.py
  sale_commission/views/account_invoice_view.xml
  sale_commission/views/sale_order_view.xml
  sale_commission/views/settlement_view.xml
  sale_commission_formula/models/account_invoice.py
  sale_commission_formula/models/sale_order.py
Labels: approved, needs review
