Repository OCA/commission, pull requests merged in 2020-07, with the labels that each got.

#245 [11.0][IMP] hr_commission: Allow to mark settlements as invoiced
  hr_commission/__manifest__.py
  hr_commission/models/__init__.py
  hr_commission/models/sale_commission_settlement.py
  hr_commission/views/sale_commission_settlement_views.xml
Labels: bot is merging ⏳

#237 [13.0][MIG] sale_commission: Migration to 13.0
  sale_commission/README.rst
  sale_commission/__init__.py
  sale_commission/__manifest__.py
  sale_commission/demo/sale_agent_demo.xml
  sale_commission/i18n/ca.po
  sale_commission/i18n/de.po
  sale_commission/i18n/es.po
  sale_commission/i18n/it.po
  sale_commission/i18n/nl_NL.po
  sale_commission/i18n/pt.po
  sale_commission/i18n/pt_BR.po
  sale_commission/i18n/pt_PT.po
  sale_commission/i18n/sale_commission.pot
  sale_commission/i18n/sl.po
  sale_commission/i18n/zh_CN.po
  sale_commission/migrations/13.0.1.0.0/noupdate_changes.xml
  sale_commission/migrations/13.0.1.0.0/post-migration.py
  sale_commission/migrations/13.0.1.0.0/pre-migration.py
  sale_commission/models/__init__.py
  sale_commission/models/account_move.py
  sale_commission/models/product_template.py
  sale_commission/models/res_partner.py
  sale_commission/models/sale_commission.py
  sale_commission/models/sale_commission_mixin.py
  sale_commission/models/sale_order.py
  sale_commission/models/settlement.py
  sale_commission/readme/CONFIGURE.rst
  sale_commission/readme/CONTRIBUTORS.rst
  sale_commission/readme/DESCRIPTION.rst
  sale_commission/readme/ROADMAP.rst
  sale_commission/readme/USAGE.rst
  sale_commission/report/__init__.py
  sale_commission/report/sale_commission_analysis_report.py
  sale_commission/report/sale_commission_analysis_report_view.xml
  sale_commission/security/ir.model.access.csv
  sale_commission/security/sale_commission_security.xml
  sale_commission/static/description/icon.png
  sale_commission/static/description/icon.svg
  sale_commission/static/description/index.html
  sale_commission/tests/__init__.py
  sale_commission/tests/test_sale_commission.py
  sale_commission/views/account_move_views.xml
  sale_commission/views/product_template_view.xml
  sale_commission/views/report_settlement_templates.xml
  sale_commission/views/res_partner_view.xml
  sale_commission/views/sale_commission_mixin_views.xml
  sale_commission/views/sale_commission_settlement_report.xml
  sale_commission/views/sale_commission_settlement_view.xml
  sale_commission/views/sale_commission_view.xml
  sale_commission/views/sale_order_view.xml
  sale_commission/wizard/__init__.py
  sale_commission/wizard/wizard_invoice.py
  sale_commission/wizard/wizard_invoice.xml
  sale_commission/wizard/wizard_settle.py
  sale_commission/wizard/wizard_settle.xml
  setup/.setuptools-odoo-make-default-ignore
  setup/README
  setup/sale_commission/odoo/addons/sale_commission
  setup/sale_commission/setup.py
Labels: bot is merging ⏳, needs review

#248 [13.0] [MIG] sale_commission_formula
  .pre-commit-config.yaml
  sale_commission_formula/README.rst
  sale_commission_formula/__init__.py
  sale_commission_formula/__manifest__.py
  sale_commission_formula/demo/commission_demo.xml
  sale_commission_formula/i18n/ca.po
  sale_commission_formula/i18n/de.po
  sale_commission_formula/i18n/el_GR.po
  sale_commission_formula/i18n/es.po
  sale_commission_formula/i18n/fi.po
  sale_commission_formula/i18n/fr.po
  sale_commission_formula/i18n/it.po
  sale_commission_formula/i18n/pt.po
  sale_commission_formula/i18n/pt_BR.po
  sale_commission_formula/i18n/pt_PT.po
  sale_commission_formula/i18n/ru.po
  sale_commission_formula/i18n/sale_commission_formula.pot
  sale_commission_formula/i18n/sl.po
  sale_commission_formula/i18n/tr.po
  sale_commission_formula/i18n/tr_TR.po
  sale_commission_formula/i18n/zh_CN.po
  sale_commission_formula/migrations/13.0.1.0.0/pre-migration.py
  sale_commission_formula/models/__init__.py
  sale_commission_formula/models/sale_commission.py
  sale_commission_formula/models/sale_commission_mixin.py
  sale_commission_formula/readme/CONTRIBUTORS.rst
  sale_commission_formula/readme/DESCRIPTION.rst
  sale_commission_formula/readme/USAGE.rst
  sale_commission_formula/static/description/icon.png
  sale_commission_formula/static/description/icon.svg
  sale_commission_formula/static/description/index.html
  sale_commission_formula/static/src/css/sale_commission_formula.css
  sale_commission_formula/tests/__init__.py
  sale_commission_formula/tests/test_commission_formula.py
  sale_commission_formula/views/sale_commission_view.xml
  setup/sale_commission_formula/odoo/addons/sale_commission_formula
  setup/sale_commission_formula/setup.py
Labels: approved, bot is merging ⏳

#249 [13.0] [MIG] sale_commission_pricelist
  sale_commission_pricelist/README.rst
  sale_commission_pricelist/__init__.py
  sale_commission_pricelist/__manifest__.py
  sale_commission_pricelist/i18n/de.po
  sale_commission_pricelist/i18n/es.po
  sale_commission_pricelist/i18n/fr.po
  sale_commission_pricelist/i18n/it.po
  sale_commission_pricelist/i18n/pt.po
  sale_commission_pricelist/i18n/pt_BR.po
  sale_commission_pricelist/i18n/sale_commission_pricelist.pot
  sale_commission_pricelist/i18n/tr.po
  sale_commission_pricelist/i18n/zh_CN.po
  sale_commission_pricelist/models/__init__.py
  sale_commission_pricelist/models/product_pricelist.py
  sale_commission_pricelist/models/sale_order.py
  sale_commission_pricelist/readme/CONTRIBUTORS.rst
  sale_commission_pricelist/readme/DESCRIPTION.rst
  sale_commission_pricelist/readme/USAGE.rst
  sale_commission_pricelist/static/description/icon.png
  sale_commission_pricelist/static/description/icon.svg
  sale_commission_pricelist/static/description/index.html
  sale_commission_pricelist/tests/__init__.py
  sale_commission_pricelist/tests/test_sale_commission_pricelist.py
  sale_commission_pricelist/views/product_pricelist_view.xml
  setup/sale_commission_pricelist/odoo/addons/sale_commission_pricelist
  setup/sale_commission_pricelist/setup.py
Labels: bot is merging ⏳
