Repository OCA/commission, pull requests merged in 2021-02, with the labels that each got.

#278 [ADD] sale_commission_delegated_partner
  sale_commission_delegated_partner/README.rst
  sale_commission_delegated_partner/__init__.py
  sale_commission_delegated_partner/__manifest__.py
  sale_commission_delegated_partner/models/__init__.py
  sale_commission_delegated_partner/models/res_partner.py
  sale_commission_delegated_partner/models/sale_commission_settlement.py
  sale_commission_delegated_partner/readme/CONTRIBUTORS.rst
  sale_commission_delegated_partner/readme/DESCRIPTION.rst
  sale_commission_delegated_partner/static/description/icon.png
  sale_commission_delegated_partner/static/description/index.html
  sale_commission_delegated_partner/tests/__init__.py
  sale_commission_delegated_partner/tests/test_sale_commission_delegate_partner.py
  sale_commission_delegated_partner/views/res_partner.xml
Labels: approved, bot is merging ⏳, ready to merge

#279 [12.0] sale_commission: add analysis view for sale orders
  sale_commission/__manifest__.py
  sale_commission/readme/CONTRIBUTORS.rst
  sale_commission/readme/USAGE.rst
  sale_commission/report/__init__.py
  sale_commission/report/sale_commission_analysis_report_view.xml
  sale_commission/report/sale_order_commission_analysis_report.py
  sale_commission/report/sale_order_commission_analysis_report_view.xml
  sale_commission/security/ir.model.access.csv
  sale_commission/security/sale_commission_security.xml
Labels: bot is merging ⏳

#284 [13.0][FIX] sale_commission: Fix tests
  sale_commission/tests/test_sale_commission.py
Labels: approved, bot is merging ⏳

#280 [12.0] IMP sale_commission allowing to filter sale orders and invoices by agents
  sale_commission/models/account_invoice.py
  sale_commission/models/sale_order.py
  sale_commission/tests/test_sale_commission.py
  sale_commission/views/account_invoice_view.xml
  sale_commission/views/sale_order_view.xml
Labels: approved, bot is merging ⏳

#286 [12.0] FIX sale_commission: wrogn model_id for "All Orders Lines Analysis" record rule
  sale_commission/__manifest__.py
  sale_commission/migrations/12.0.3.1.1/post-migration.py
  sale_commission/security/sale_commission_security.xml
Labels: bot is merging ⏳

#287 [13.0][IMP] sale_commission: Add optional in commission_status field related to order view
  sale_commission/views/sale_order_view.xml
Labels: approved, bot is merging ⏳

#285 [13.0][MIG] hr_commission: Migration to 13.0
  hr_commission/README.rst
  hr_commission/__init__.py
  hr_commission/__manifest__.py
  hr_commission/i18n/es.po
  hr_commission/i18n/hr_commission.pot
  hr_commission/i18n/pt_BR.po
  hr_commission/models/__init__.py
  hr_commission/models/hr_employee.py
  hr_commission/models/res_partner.py
  hr_commission/models/sale_commission_settlement.py
  hr_commission/readme/CONTRIBUTORS.rst
  hr_commission/readme/DESCRIPTION.rst
  hr_commission/readme/ROADMAP.rst
  hr_commission/static/description/icon.png
  hr_commission/static/description/icon.svg
  hr_commission/static/description/index.html
  hr_commission/tests/__init__.py
  hr_commission/tests/test_hr_commission.py
  hr_commission/views/res_partner_view.xml
  hr_commission/views/sale_commission_settlement_views.xml
  setup/hr_commission/odoo/addons/hr_commission
  setup/hr_commission/setup.py
Labels: bot is merging ⏳
