Repository OCA/commission, pull requests merged in 2021-07, with the labels that each got.

#309 [13.0] FIX sale_commission preventing to cancel invoice with settled commiss…
  sale_commission/models/account_move.py
Labels: approved, bot is merging ⏳

#310 [14.0] FIX sale_commission preventing to cancel invoice with settled commiss…
  sale_commission/models/account_move.py
Labels: approved, bot is merging ⏳

#312 [IMP] sale_commission: Allow to group invoices
  sale_commission/__manifest__.py
  sale_commission/migrations/13.0.1.6.0/pre-migration.py
  sale_commission/models/account_move.py
  sale_commission/models/settlement.py
  sale_commission/tests/test_sale_commission.py
  sale_commission/views/account_move_views.xml
  sale_commission/wizard/wizard_invoice.py
  sale_commission/wizard/wizard_invoice.xml
Labels: approved, bot is merging ⏳, ready to merge

#314 [FIX] sale_commission
  sale_commission/tests/test_sale_commission.py
Labels: approved, bot is merging ⏳, bug, needs review

#315 [14.0][FIX] sale_commission
  sale_commission/models/account_move.py
Labels: approved, bot is merging ⏳, bug, needs review
