Repository OCA/commission, pull requests merged in 2021-05, with the labels that each got.

#282 [13.0][FIX] Context overriden from invoice_line_ids
  sale_commission/models/account_move.py
  sale_commission/views/account_move_views.xml
Labels: bot is merging ⏳

#260 [12.0][MIG] contract_commission migration
  contract_commission/README.rst
  contract_commission/__init__.py
  contract_commission/__manifest__.py
  contract_commission/i18n/ca.po
  contract_commission/i18n/contract_commission.pot
  contract_commission/i18n/de.po
  contract_commission/i18n/el_GR.po
  contract_commission/i18n/es.po
  contract_commission/i18n/es_MX.po
  contract_commission/i18n/fr.po
  contract_commission/i18n/it.po
  contract_commission/i18n/pt_BR.po
  contract_commission/i18n/sl.po
  contract_commission/models/__init__.py
  contract_commission/models/contract_line.py
  contract_commission/readme/CONFIGURE.rst
  contract_commission/readme/CONTRIBUTORS.rst
  contract_commission/readme/DESCRIPTION.rst
  contract_commission/readme/USAGE.rst
  contract_commission/static/description/banner.png
  contract_commission/static/description/icon.png
  contract_commission/static/description/icon.svg
  contract_commission/static/description/index.html
  contract_commission/tests/__init__.py
  contract_commission/tests/test_contract_commission.py
  oca_dependencies.txt
Labels: approved, bot is merging ⏳, ready to merge

#302 [14.0][MIG] sale_commission: Migration to 14.0
  sale_commission/README.rst
  sale_commission/__init__.py
  sale_commission/__manifest__.py
  sale_commission/demo/sale_agent_demo.xml
  sale_commission/i18n/ca.po
  sale_commission/i18n/de.po
  sale_commission/i18n/es.po
  sale_commission/i18n/es_AR.po
  sale_commission/i18n/it.po
  sale_commission/i18n/nl_NL.po
  sale_commission/i18n/pt.po
  sale_commission/i18n/pt_BR.po
  sale_commission/i18n/pt_PT.po
  sale_commission/i18n/sale_commission.pot
  sale_commission/i18n/sl.po
  sale_commission/i18n/zh_CN.po
  sale_commission/models/__init__.py
  sale_commission/models/account_move.py
  sale_commission/models/product_template.py
  sale_commission/models/res_partner.py
  sale_commission/models/sale_commission.py
  sale_commission/models/sale_commission_mixin.py
  sale_commission/models/sale_order.py
  sale_commission/models/settlement.py
  sale_commission/readme/CONFIGURE.rst
  sale_commission/readme/CONTRIBUTORS.rst
  sale_commission/readme/DESCRIPTION.rst
  sale_commission/readme/ROADMAP.rst
  sale_commission/readme/USAGE.rst
  sale_commission/report/__init__.py
  sale_commission/report/sale_commission_analysis_report.py
  sale_commission/report/sale_commission_analysis_report_view.xml
  sale_commission/security/ir.model.access.csv
  sale_commission/security/sale_commission_security.xml
  sale_commission/static/description/icon.png
  sale_commission/static/description/icon.svg
  sale_commission/static/description/index.html
  sale_commission/tests/__init__.py
  sale_commission/tests/test_sale_commission.py
  sale_commission/views/account_move_views.xml
  sale_commission/views/product_template_view.xml
  sale_commission/views/report_settlement_templates.xml
  sale_commission/views/res_partner_view.xml
  sale_commission/views/sale_commission_mixin_views.xml
  sale_commission/views/sale_commission_settlement_report.xml
  sale_commission/views/sale_commission_settlement_view.xml
  sale_commission/views/sale_commission_view.xml
  sale_commission/views/sale_order_view.xml
  sale_commission/wizard/__init__.py
  sale_commission/wizard/wizard_invoice.py
  sale_commission/wizard/wizard_invoice.xml
  sale_commission/wizard/wizard_settle.py
  sale_commission/wizard/wizard_settle.xml
Labels: approved, bot is merging ⏳, migration, needs review
