Repository OCA/commission, pull requests merged in 2022-05, with the labels that each got.

#353 [13.0][IMP] sale_commission: New bi-weekly settlement period
  sale_commission/README.rst
  sale_commission/models/res_partner.py
  sale_commission/readme/CONFIGURE.rst
  sale_commission/static/description/index.html
  sale_commission/tests/test_sale_commission.py
  sale_commission/wizard/wizard_settle.py
Labels: approved, ready to merge, bot is merging ⏳

#358 Forward port missing commits. Forwarding all missing commits from 13.0 to 14.0
  sale_commission/README.rst
  sale_commission/__manifest__.py
  sale_commission/migrations/14.0.1.3.0/pre-migration.py
  sale_commission/models/account_move.py
  sale_commission/models/res_partner.py
  sale_commission/models/settlement.py
  sale_commission/readme/CONFIGURE.rst
  sale_commission/static/description/index.html
  sale_commission/tests/test_sale_commission.py
  sale_commission/views/account_move_views.xml
  sale_commission/wizard/wizard_invoice.py
  sale_commission/wizard/wizard_invoice.xml
  sale_commission/wizard/wizard_settle.py
Labels: approved, bot is merging ⏳

#357 [FIX] sale_commission_geo_assign: license
  sale_commission_geo_assign/__manifest__.py
Labels: bot is merging ⏳

#360 [14.0][FIX] sale_commission: compute amount after changing commission, fixes #355
  sale_commission/models/sale_order.py
Labels: approved, bot is merging ⏳
