Repository OCA/commission, pull requests merged in 2023-08, with the labels that each got.

#426 [15.0][OU-ADD] commission: Migration scripts
  commission/migrations/15.0.2.0.0/post-migration.py
  commission/migrations/15.0.2.0.0/pre-migration.py
Labels: approved

#432 [16.0][MIG] hr_commission
  hr_commission/README.rst
  hr_commission/__init__.py
  hr_commission/__manifest__.py
  hr_commission/i18n/ca.po
  hr_commission/i18n/ca_ES.po
  hr_commission/i18n/es.po
  hr_commission/i18n/hr_commission.pot
  hr_commission/i18n/pt_BR.po
  hr_commission/models/__init__.py
  hr_commission/models/hr_employee.py
  hr_commission/models/res_partner.py
  hr_commission/models/sale_commission_settlement.py
  hr_commission/readme/CONTRIBUTORS.rst
  hr_commission/readme/DESCRIPTION.rst
  hr_commission/readme/ROADMAP.rst
  hr_commission/static/description/icon.png
  hr_commission/static/description/icon.svg
  hr_commission/static/description/index.html
  hr_commission/tests/__init__.py
  hr_commission/tests/test_hr_commission.py
  hr_commission/views/res_partner_view.xml
  hr_commission/views/sale_commission_settlement_views.xml
  setup/hr_commission/odoo/addons/hr_commission
  setup/hr_commission/setup.py
Labels: approved, bot is merging ⏳

#443 [IMP] sale_commission_product_criteria: no need to order items by id
  sale_commission_product_criteria/models/sale_commission_line_mixin.py
  sale_commission_product_criteria/views/views.xml
Labels: bot is merging ⏳

#431 [16.0] [IMP] commission: Settlement mail thread activity and report
  account_commission/views/report_settlement_templates.xml
  commission/models/commission_settlement.py
  commission/reports/report_settlement_templates.xml
  commission/tests/test_commission.py
  commission/views/commission_settlement_views.xml
Labels: bot is merging ⏳

#411 [16.0][FIX] account_commission: Regenerate agents button invisibility
  account_commission/views/account_move_views.xml
Labels: bot is merging ⏳, stale

#415 [16.0][FIX] account_commission: button typo and period string
  account_commission/i18n/account_commission.pot
  account_commission/i18n/hr.po
  account_commission/i18n/ja.po
  account_commission/models/commission_settlement.py
  account_commission/wizards/wizard_invoice.xml
Labels: bot is merging ⏳, stale

#416 [16.0][FIX] account_commission: revert settlement state to settled when deleting draft settlement invoice
  account_commission/models/account_move.py
  account_commission/tests/test_account_commission.py
Labels: bot is merging ⏳, stale

#445 [15.0] [IMP] commission: Settlement mail thread activity and report
  account_commission/views/report_settlement_templates.xml
  commission/models/commission_settlement.py
  commission/reports/report_settlement_templates.xml
  commission/tests/test_commission.py
  commission/views/commission_settlement_views.xml
Labels: bot is merging ⏳

#444 [15.0][FIX] account_commission: revert settlement state to settled when deleting draft settlement invoice
  account_commission/models/account_move.py
  account_commission/tests/test_account_commission.py
Labels: bot is merging ⏳

#440 [15.0][IMP] account_commission: skip not invoice lines
  account_commission/models/account_move.py
Labels: bot is merging ⏳

#433 [16.0][MIG] sale_commission_salesman
  sale_commission_salesman/README.rst
  sale_commission_salesman/__init__.py
  sale_commission_salesman/__manifest__.py
  sale_commission_salesman/i18n/ca.po
  sale_commission_salesman/i18n/es.po
  sale_commission_salesman/i18n/es_AR.po
  sale_commission_salesman/i18n/it.po
  sale_commission_salesman/i18n/sale_commission_salesman.pot
  sale_commission_salesman/models/__init__.py
  sale_commission_salesman/models/account_move.py
  sale_commission_salesman/models/res_partner.py
  sale_commission_salesman/models/sale_order.py
  sale_commission_salesman/readme/CONFIGURE.rst
  sale_commission_salesman/readme/CONTRIBUTORS.rst
  sale_commission_salesman/readme/CREDITS.rst
  sale_commission_salesman/readme/DESCRIPTION.rst
  sale_commission_salesman/readme/ROADMAP.rst
  sale_commission_salesman/readme/USAGE.rst
  sale_commission_salesman/static/description/icon.png
  sale_commission_salesman/static/description/icon.svg
  sale_commission_salesman/static/description/index.html
  sale_commission_salesman/tests/__init__.py
  sale_commission_salesman/tests/test_sale_commission_salesman.py
  sale_commission_salesman/views/res_partner_views.xml
  setup/sale_commission_salesman/odoo/addons/sale_commission_salesman
  setup/sale_commission_salesman/setup.py
Labels: bot is merging ⏳

#447 [15.0][FIX] account_commission: redefine partner can cause issue
  account_commission/models/commission_settlement.py
Labels: bot is merging ⏳
