Repository OCA/commission, pull requests merged in 2023-11, with the labels that each got.

#472 [14.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
Labels: help wanted, needs review

#478 [14.0] ocabot update dotfiles
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  sale_commission/i18n/ca.po
  sale_commission/i18n/de.po
  sale_commission/i18n/sl.po
  sale_commission/views/account_move_views.xml
  sale_commission/views/res_partner_view.xml
  sale_commission/views/sale_commission_settlement_view.xml
  sale_commission/views/sale_commission_view.xml
  sale_commission/views/sale_order_view.xml
  sale_commission_agent_restrict/views/sale_order_view.xml
  sale_commission_product_criteria/views/views.xml
  sale_commission_product_criteria_domain/views/views.xml
Labels: approved, bot is merging ⏳

#482 [IMP] sale_commission_geo_assign_product_domain: maintainers
  sale_commission_geo_assign_product_domain/README.rst
  sale_commission_geo_assign_product_domain/__manifest__.py
  sale_commission_geo_assign_product_domain/static/description/index.html
Labels: bot is merging ⏳

#481 [14.0][FIX] sale_commission_product_criteria_domain: multicompany item agent
  sale_commission_product_criteria_domain/README.rst
  sale_commission_product_criteria_domain/__manifest__.py
  sale_commission_product_criteria_domain/security/sale_commission_security.xml
  sale_commission_product_criteria_domain/static/description/index.html
Labels: approved, bot is merging ⏳

#446 [15.0][IMP] commission: multi-currency support
  account_commission/models/account_move.py
  account_commission/models/commission_settlement.py
  account_commission/readme/CONTRIBUTORS.rst
  account_commission/tests/test_account_commission.py
  account_commission/views/account_move_views.xml
  commission/README.rst
  commission/readme/CONTRIBUTORS.rst
  commission/readme/ROADMAP.rst
  commission/static/description/index.html
  commission/tests/test_commission.py
  commission/views/commission_settlement_views.xml
  commission/wizards/commission_make_settle.py
Labels: approved, ready to merge, bot is merging ⏳

#479 [16.0][FW][IMP] commission: multi-currency support
  account_commission/README.rst
  account_commission/models/account_move.py
  account_commission/models/commission_settlement.py
  account_commission/readme/CONTRIBUTORS.rst
  account_commission/static/description/index.html
  account_commission/tests/test_account_commission.py
  account_commission/views/account_move_views.xml
  commission/README.rst
  commission/readme/CONTRIBUTORS.rst
  commission/readme/ROADMAP.rst
  commission/static/description/index.html
  commission/tests/test_commission.py
  commission/views/commission_settlement_views.xml
  commission/wizards/commission_make_settle.py
Labels: bot is merging ⏳

#476 [15.0][FIX] account_commission: mandatory fields cannot be set to False.
  account_commission/models/account_move.py
Labels: approved, bot is merging ⏳

#483 [16.0][FIX] account_commission: mandatory fields cannot be set to False.
  account_commission/models/account_move.py
Labels: bot is merging ⏳

#484 [15.0][FIX] hr_commission: Possibility to have several records in constraint
  hr_commission/models/res_partner.py
Labels: bot is merging ⏳
