Repository OCA/commission, pull requests merged in 2023-12, with the labels that each got.

#487 [FIX] sale_commission_geo_assign_product_domain: ondelete group
  sale_commission_geo_assign_product_domain/models/res_partner.py
  sale_commission_geo_assign_product_domain/models/res_partner_commission_group.py
Labels: approved, bot is merging ⏳

#486 [14.0][ADD] sale_commission_partial_payment: Commission based on payment amount
  sale_commission_partial_settlement/README.rst
  sale_commission_partial_settlement/__init__.py
  sale_commission_partial_settlement/__manifest__.py
  sale_commission_partial_settlement/models/__init__.py
  sale_commission_partial_settlement/models/account_move.py
  sale_commission_partial_settlement/models/account_partial_reconcile.py
  sale_commission_partial_settlement/models/sale_commission.py
  sale_commission_partial_settlement/models/settlement.py
  sale_commission_partial_settlement/readme/CONTRIBUTORS.rst
  sale_commission_partial_settlement/readme/DESCRIPTION.rst
  sale_commission_partial_settlement/readme/USAGE.rst
  sale_commission_partial_settlement/security/ir.model.access.csv
  sale_commission_partial_settlement/static/description/icon.png
  sale_commission_partial_settlement/static/description/index.html
  sale_commission_partial_settlement/tests/__init__.py
  sale_commission_partial_settlement/tests/test_partial_settlement.py
  sale_commission_partial_settlement/views/sale_commission_view.xml
  sale_commission_partial_settlement/wizard/__init__.py
  sale_commission_partial_settlement/wizard/wizard_settle.py
  setup/sale_commission_partial_settlement/odoo/addons/sale_commission_partial_settlement
  setup/sale_commission_partial_settlement/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#490 [14.0] [IMP] sale_commission: Clarify selection fields
  sale_commission/README.rst
  sale_commission/models/sale_commission.py
  sale_commission/readme/CONFIGURE.rst
  sale_commission/static/description/index.html
Labels: approved, bot is merging ⏳

#492 [16.0] [FW-PORT] commission: Clarify selection fields
  account_commission/models/commission.py
  commission/README.rst
  commission/models/commission.py
  commission/readme/CONFIGURE.rst
  commission/static/description/index.html
Labels: bot is merging ⏳

#491 [15.0] [FW-PORT] commission: Clarify selection fields
  account_commission/models/commission.py
  commission/README.rst
  commission/models/commission.py
  commission/readme/CONFIGURE.rst
  commission/static/description/index.html
Labels: bot is merging ⏳
