Repository OCA/commission, pull requests merged in 2023-09, with the labels that each got.

#423 [ADD] sale_commission_product_based
  sale_commission_product_based/README.rst
  sale_commission_product_based/__init__.py
  sale_commission_product_based/__manifest__.py
  sale_commission_product_based/i18n/it.po
  sale_commission_product_based/models/__init__.py
  sale_commission_product_based/models/product_rule.py
  sale_commission_product_based/models/sale_commission.py
  sale_commission_product_based/models/sale_commission_line_mixin.py
  sale_commission_product_based/readme/CONFIGURE.rst
  sale_commission_product_based/readme/CONTRIBUTORS.rst
  sale_commission_product_based/readme/DESCRIPTION.rst
  sale_commission_product_based/readme/USAGE.rst
  sale_commission_product_based/security/ir.model.access.csv
  sale_commission_product_based/static/description/index.html
  sale_commission_product_based/tests/__init__.py
  sale_commission_product_based/tests/test_product_fallback.py
  sale_commission_product_based/views/sale_commission_views.xml
  setup/sale_commission_product_based/odoo/addons/sale_commission_product_based
  setup/sale_commission_product_based/setup.py
Labels: approved, ready to merge, bot is merging ⏳, stale

#453 [14.0][IMP][FIX] sale_commission_product_criteria[_domain]: permission fixes
  sale_commission_product_criteria/security/ir.model.access.csv
  sale_commission_product_criteria_domain/views/views.xml
Labels: approved, bot is merging ⏳

#450 [14.0][FIX] sale_commission_agent_restrict: do not deactivate base rules
  sale_commission_agent_restrict/__init__.py
  sale_commission_agent_restrict/__manifest__.py
  sale_commission_agent_restrict/hooks.py
  sale_commission_agent_restrict/migrations/14.0.2.0.0/pre-migrate.py
  sale_commission_agent_restrict/models/__init__.py
  sale_commission_agent_restrict/models/mail_thread.py
  sale_commission_agent_restrict/models/res_partner.py
  sale_commission_agent_restrict/models/res_users.py
  sale_commission_agent_restrict/models/sale.py
  sale_commission_agent_restrict/readme/CONTRIBUTORS.rst
  sale_commission_agent_restrict/security/security.xml
  sale_commission_agent_restrict/tests/test_sale_commission_agent_restrict.py
  sale_commission_agent_restrict/views/res_partner_views.xml
  sale_commission_agent_restrict/views/sale_order_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#451 [14.0] [ADD] sale_commission_geo_assign_product_domain
  sale_commission_geo_assign/wizard/wizard_geo_assign_partner.py
  sale_commission_geo_assign_product_domain/README.rst
  sale_commission_geo_assign_product_domain/__init__.py
  sale_commission_geo_assign_product_domain/__manifest__.py
  sale_commission_geo_assign_product_domain/models/__init__.py
  sale_commission_geo_assign_product_domain/models/res_partner.py
  sale_commission_geo_assign_product_domain/models/res_partner_commission_group.py
  sale_commission_geo_assign_product_domain/readme/CONFIGURE.rst
  sale_commission_geo_assign_product_domain/readme/CONTRIBUTORS.rst
  sale_commission_geo_assign_product_domain/readme/DESCRIPTION.rst
  sale_commission_geo_assign_product_domain/readme/USAGE.rst
  sale_commission_geo_assign_product_domain/security/ir.model.access.csv
  sale_commission_geo_assign_product_domain/static/description/icon.png
  sale_commission_geo_assign_product_domain/static/description/index.html
  sale_commission_geo_assign_product_domain/tests/__init__.py
  sale_commission_geo_assign_product_domain/tests/test_sale_commission_geo_assign_product_domain.py
  sale_commission_geo_assign_product_domain/views/res_partner_view.xml
  sale_commission_geo_assign_product_domain/wizards/__init__.py
  sale_commission_geo_assign_product_domain/wizards/wizard_geo_assign_partner.py
  setup/sale_commission_geo_assign_product_domain/odoo/addons/sale_commission_geo_assign_product_domain
  setup/sale_commission_geo_assign_product_domain/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#454 [14.0] [IMP] sale_commission_geo_assign
  sale_commission_geo_assign/README.rst
  sale_commission_geo_assign/models/res_partner.py
  sale_commission_geo_assign/readme/CONTRIBUTORS.rst
  sale_commission_geo_assign/readme/DESCRIPTION.rst
  sale_commission_geo_assign/readme/USAGE.rst
  sale_commission_geo_assign/static/description/index.html
  sale_commission_geo_assign/tests/test_sale_commission_geo_assign.py
  sale_commission_geo_assign/views/res_partner_view.xml
  sale_commission_geo_assign/wizard/wizard_geo_assign_partner.py
  sale_commission_geo_assign/wizard/wizard_geo_assign_partner_view.xml
Labels: approved, bot is merging ⏳

#452 [14.0][FIX] sale_commission_product_criteria_domain: onchange agents withs …
  sale_commission_product_criteria_domain/models/commission.py
  sale_commission_product_criteria_domain/models/partner.py
  sale_commission_product_criteria_domain/readme/DESCRIPTION.rst
  sale_commission_product_criteria_domain/tests/test_sale_commission_product_criteria_domain.py
  sale_commission_product_criteria_domain/views/views.xml
Labels: approved, bot is merging ⏳

#441 [14 0] [IMP] sale_commission: possibility to add payment date limit on settle commissions
  sale_commission/models/account_move.py
  sale_commission/readme/CONTRIBUTORS.rst
  sale_commission/readme/USAGE.rst
  sale_commission/tests/test_sale_commission.py
  sale_commission/wizard/wizard_settle.py
  sale_commission/wizard/wizard_settle.xml
Labels: approved, ready to merge, bot is merging ⏳

#456 [14.0][FIX] sale_commission_geo_assign_product_domain: upd security and groups in view
  sale_commission_geo_assign_product_domain/__manifest__.py
  sale_commission_geo_assign_product_domain/security/ir.model.access.csv
  sale_commission_geo_assign_product_domain/views/res_partner_view.xml
Labels: bot is merging ⏳

#458 [15.0][FIX] sale_commission_salesman, fix singleton issue
  sale_commission_salesman/models/account_move.py
Labels: bot is merging ⏳
