Repository OCA/commission, pull requests merged in 2024-11, with the labels that each got.

#571 [16.0][FIX] sale_commission_product_criteria
  sale_commission_product_criteria/models/commission.py
  sale_commission_product_criteria/tests/test_sale_commission_product_criteria.py
  sale_commission_product_criteria_discount/README.rst
  sale_commission_product_criteria_discount/__manifest__.py
  sale_commission_product_criteria_discount/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#576 [14.0][FIX] account_commission: revert settlement in invoiced state to settled when deleting settlement invoice
  sale_commission/models/account_move.py
  sale_commission/tests/test_sale_commission.py
Labels: bot is merging ⏳

#575 [14.0][FIX] sale_commission_partial_settlement: handle settlement deletion
  sale_commission_partial_settlement/__manifest__.py
  sale_commission_partial_settlement/migrations/14.0.1.1.0/post-migrate.py
  sale_commission_partial_settlement/models/__init__.py
  sale_commission_partial_settlement/models/account_invoice_line_agent.py
  sale_commission_partial_settlement/models/account_invoice_line_agent_partial.py
  sale_commission_partial_settlement/models/account_partial_reconcile.py
  sale_commission_partial_settlement/models/sale_commission_settlement.py
  sale_commission_partial_settlement/models/sale_commission_settlement_line.py
  sale_commission_partial_settlement/wizard/wizard_settle.py
Labels: approved, bot is merging ⏳

#579 [14.0][IMP]sale_commission_partial_settlement: save settlement wizard date
  sale_commission_partial_settlement/__manifest__.py
  sale_commission_partial_settlement/models/__init__.py
  sale_commission_partial_settlement/models/res_company.py
  sale_commission_partial_settlement/models/res_config_settings.py
  sale_commission_partial_settlement/models/sale_commission_settlement.py
  sale_commission_partial_settlement/views/res_config_settings_view.xml
  sale_commission_partial_settlement/views/sale_commission_settlement_view.xml
  sale_commission_partial_settlement/wizard/wizard_settle.py
Labels: approved, bot is merging ⏳

#580 [14.0][FIX] sale_commission_product_criteria_domain: onchange partner agents
  sale_commission_product_criteria_domain/models/partner.py
Labels: approved, bot is merging ⏳
