Repository OCA/commission, pull requests merged in 2024-10, with the labels that each got.

#568 [14.0][FIX]sale_commission_product_criteria: ignore error on create
  sale_commission_product_criteria/models/commission.py
  sale_commission_product_criteria/tests/test_sale_commission_product_criteria.py
  sale_commission_product_criteria_discount/README.rst
  sale_commission_product_criteria_discount/__manifest__.py
  sale_commission_product_criteria_discount/static/description/index.html
Labels: bot is merging ⏳

#569 [IMP] sale_commission_product_criteria: print commission value on settlement report
  sale_commission_product_criteria/README.rst
  sale_commission_product_criteria/__manifest__.py
  sale_commission_product_criteria/models/__init__.py
  sale_commission_product_criteria/models/settlement.py
  sale_commission_product_criteria/reports/report_settlement_template.xml
  sale_commission_product_criteria/static/description/index.html
Labels: bot is merging ⏳

#570 [14.0][IMP] sale_commission: print partial and document total in report
  sale_commission/views/report_settlement_templates.xml
Labels: approved, ready to merge, bot is merging ⏳

#554 [14.0][ADD]sale_commission_queued: add queue to settlement wizard
  sale_commission_queued/README.rst
  sale_commission_queued/__manifest__.py
  sale_commission_queued/readme/CONTRIBUTORS.rst
  sale_commission_queued/readme/USAGE.rst
  sale_commission_queued/static/description/index.html
  sale_commission_queued/wizard/__init__.py
  sale_commission_queued/wizard/wizard_settle.py
  sale_commission_queued/wizard/wizard_settle.xml
Labels: approved, bot is merging ⏳

#572 [15.0][IMP] sale_commission: print partial and document total in report
  account_commission/views/report_settlement_templates.xml
  commission/reports/report_settlement_templates.xml
Labels: approved, ready to merge, bot is merging ⏳
