Repository OCA/commission, pull requests merged in 2024-05, with the labels that each got.

#522 [14.0][FIX] sale_commission_salesman: fix singleton issue
  sale_commission_salesman/models/account_move.py
Labels: approved, bot is merging ⏳

#521 [17.0][MIG] commission_formula: Migration to 17.0
  commission_formula/README.rst
  commission_formula/__init__.py
  commission_formula/__manifest__.py
  commission_formula/demo/commission_demo.xml
  commission_formula/i18n/ca.po
  commission_formula/i18n/commission_formula.pot
  commission_formula/i18n/de.po
  commission_formula/i18n/el_GR.po
  commission_formula/i18n/es.po
  commission_formula/i18n/es_AR.po
  commission_formula/i18n/fi.po
  commission_formula/i18n/fr.po
  commission_formula/i18n/it.po
  commission_formula/i18n/pt.po
  commission_formula/i18n/pt_BR.po
  commission_formula/i18n/pt_PT.po
  commission_formula/i18n/ru.po
  commission_formula/i18n/sale_commission_formula.pot
  commission_formula/i18n/sl.po
  commission_formula/i18n/tr.po
  commission_formula/i18n/tr_TR.po
  commission_formula/i18n/zh_CN.po
  commission_formula/models/__init__.py
  commission_formula/models/commission.py
  commission_formula/models/commission_mixin.py
  commission_formula/pyproject.toml
  commission_formula/readme/CONTRIBUTORS.md
  commission_formula/readme/DESCRIPTION.md
  commission_formula/readme/USAGE.md
  commission_formula/static/description/icon.png
  commission_formula/static/description/icon.svg
  commission_formula/static/description/index.html
  commission_formula/static/src/css/commission_formula.css
  commission_formula/views/commission_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#523 [14.0][IMP]sale_commission_geo_assign: add required group to docs
  sale_commission_geo_assign/README.rst
  sale_commission_geo_assign/readme/CONFIGURE.rst
  sale_commission_geo_assign/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#526 [17.0] [FIX] commission: partner view agent
  commission/views/res_partner_views.xml
Labels: approved, bot is merging ⏳

#529 [14.0] [IMP] sale_commission_geo_assign: add maintainers
  sale_commission_geo_assign/README.rst
  sale_commission_geo_assign/__manifest__.py
  sale_commission_geo_assign/static/description/index.html
Labels: bot is merging ⏳

#527 [14.0] [FIX] sale_commission_geo_assign: reset item_agent_ids on replace
  sale_commission_geo_assign/wizard/wizard_geo_assign_partner.py
Labels: approved, bot is merging ⏳

#524 [17.0] [MIG] account_commission: Migration to 17.0
  account_commission/README.rst
  account_commission/__init__.py
  account_commission/__manifest__.py
  account_commission/data/menuitem_data.xml
  account_commission/i18n/account_commission.pot
  account_commission/i18n/es.po
  account_commission/i18n/hr.po
  account_commission/i18n/it.po
  account_commission/i18n/ja.po
  account_commission/i18n/pt.po
  account_commission/i18n/pt_BR.po
  account_commission/models/__init__.py
  account_commission/models/account_move.py
  account_commission/models/commission.py
  account_commission/models/commission_settlement.py
  account_commission/pyproject.toml
  account_commission/readme/CONFIGURE.md
  account_commission/readme/CONTRIBUTORS.md
  account_commission/readme/DESCRIPTION.md
  account_commission/readme/USAGE.md
  account_commission/report/__init__.py
  account_commission/report/commission_analysis.py
  account_commission/report/commission_analysis_view.xml
  account_commission/security/account_commission_security.xml
  account_commission/security/ir.model.access.csv
  account_commission/static/description/icon.png
  account_commission/static/description/icon.svg
  account_commission/static/description/index.html
  account_commission/tests/__init__.py
  account_commission/tests/test_account_commission.py
  account_commission/views/account_move_views.xml
  account_commission/views/commission_settlement_views.xml
  account_commission/views/commission_views.xml
  account_commission/views/report_settlement_templates.xml
  account_commission/wizards/__init__.py
  account_commission/wizards/commission_make_settle.py
  account_commission/wizards/wizard_invoice.py
  account_commission/wizards/wizard_invoice.xml
Labels: approved, ready to merge, bot is merging ⏳

#528 [14.0] [IMP] sale_commission_geo_assign_product_domain: add tree view
  sale_commission_geo_assign_product_domain/__manifest__.py
  sale_commission_geo_assign_product_domain/views/res_partner_commission_group_view.xml
Labels: approved, bot is merging ⏳

#498 [17.0][MIG] sale_commission: Migration to 17.0
  sale_commission/README.rst
  sale_commission/__init__.py
  sale_commission/__manifest__.py
  sale_commission/i18n/es.po
  sale_commission/i18n/it.po
  sale_commission/i18n/ja.po
  sale_commission/i18n/pt_BR.po
  sale_commission/i18n/sale_commission.pot
  sale_commission/models/__init__.py
  sale_commission/models/sale_order.py
  sale_commission/pyproject.toml
  sale_commission/readme/CONTRIBUTORS.md
  sale_commission/readme/DESCRIPTION.md
  sale_commission/readme/USAGE.md
  sale_commission/security/ir.model.access.csv
  sale_commission/static/description/icon.png
  sale_commission/static/description/icon.svg
  sale_commission/static/description/index.html
  sale_commission/tests/__init__.py
  sale_commission/tests/test_sale_commission.py
  sale_commission/views/sale_order_view.xml
Labels: approved, ready to merge, bot is merging ⏳
