Repository OCA/commission, pull requests merged in 2024-06, with the labels that each got.

#525 [17.0] [MIG] hr_commission: Migration to 17.0
  hr_commission/README.rst
  hr_commission/__init__.py
  hr_commission/__manifest__.py
  hr_commission/i18n/ca.po
  hr_commission/i18n/ca_ES.po
  hr_commission/i18n/es.po
  hr_commission/i18n/hr_commission.pot
  hr_commission/i18n/it.po
  hr_commission/i18n/pt_BR.po
  hr_commission/models/__init__.py
  hr_commission/models/hr_employee.py
  hr_commission/models/res_partner.py
  hr_commission/models/sale_commission_settlement.py
  hr_commission/pyproject.toml
  hr_commission/readme/CONTRIBUTORS.md
  hr_commission/readme/DESCRIPTION.md
  hr_commission/readme/ROADMAP.md
  hr_commission/static/description/icon.png
  hr_commission/static/description/icon.svg
  hr_commission/static/description/index.html
  hr_commission/tests/__init__.py
  hr_commission/tests/test_hr_commission.py
  hr_commission/views/res_partner_view.xml
  hr_commission/views/sale_commission_settlement_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#466 [16.0][MIG] sale_commission_product_criteria_discount
  sale_commission_product_criteria_discount/README.rst
  sale_commission_product_criteria_discount/__init__.py
  sale_commission_product_criteria_discount/__manifest__.py
  sale_commission_product_criteria_discount/demo/demo_data.xml
  sale_commission_product_criteria_discount/i18n/it.po
  sale_commission_product_criteria_discount/i18n/sale_commission_product_criteria_discount.pot
  sale_commission_product_criteria_discount/models/__init__.py
  sale_commission_product_criteria_discount/models/commission.py
  sale_commission_product_criteria_discount/models/res_config_settings.py
  sale_commission_product_criteria_discount/models/sale.py
  sale_commission_product_criteria_discount/readme/CONTRIBUTORS.rst
  sale_commission_product_criteria_discount/readme/DESCRIPTION.rst
  sale_commission_product_criteria_discount/readme/USAGE.rst
  sale_commission_product_criteria_discount/security/base_groups.xml
  sale_commission_product_criteria_discount/static/description/icon.png
  sale_commission_product_criteria_discount/static/description/index.html
  sale_commission_product_criteria_discount/tests/__init__.py
  sale_commission_product_criteria_discount/tests/test_sale_commission_product_criteria.py
  sale_commission_product_criteria_discount/views/res_config_settings_views.xml
  sale_commission_product_criteria_discount/views/views.xml
  setup/sale_commission_product_criteria_discount/odoo/addons/sale_commission_product_criteria_discount
  setup/sale_commission_product_criteria_discount/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#467 [16.0][MIG] sale_commission_product_criteria_domain
  sale_commission_product_criteria_domain/README.rst
  sale_commission_product_criteria_domain/__init__.py
  sale_commission_product_criteria_domain/__manifest__.py
  sale_commission_product_criteria_domain/demo/demo_data.xml
  sale_commission_product_criteria_domain/i18n/it.po
  sale_commission_product_criteria_domain/i18n/sale_commission_product_criteria_domain.pot
  sale_commission_product_criteria_domain/models/__init__.py
  sale_commission_product_criteria_domain/models/account_invoice_line_agent.py
  sale_commission_product_criteria_domain/models/commission.py
  sale_commission_product_criteria_domain/models/commission_group.py
  sale_commission_product_criteria_domain/models/partner.py
  sale_commission_product_criteria_domain/models/sale_commission_line_mixin.py
  sale_commission_product_criteria_domain/models/sale_order_line_agent.py
  sale_commission_product_criteria_domain/readme/CONTRIBUTORS.rst
  sale_commission_product_criteria_domain/readme/DESCRIPTION.rst
  sale_commission_product_criteria_domain/readme/USAGE.rst
  sale_commission_product_criteria_domain/security/ir.model.access.csv
  sale_commission_product_criteria_domain/static/description/icon.png
  sale_commission_product_criteria_domain/static/description/index.html
  sale_commission_product_criteria_domain/tests/__init__.py
  sale_commission_product_criteria_domain/tests/test_sale_commission_product_criteria_domain.py
  sale_commission_product_criteria_domain/views/views.xml
  setup/sale_commission_product_criteria_domain/odoo/addons/sale_commission_product_criteria_domain
  setup/sale_commission_product_criteria_domain/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#533 [FIX] sale_commission_product_criteria_domain: Use current record
  sale_commission_product_criteria_domain/models/commission_group.py
  sale_commission_product_criteria_domain/models/partner.py
Labels: bot is merging ⏳

#532 [14.0][FIX] sale_commission_product_criteria_domain: not agent anymore - cl…
  sale_commission_product_criteria_domain/__manifest__.py
  sale_commission_product_criteria_domain/models/account_invoice_line_agent.py
  sale_commission_product_criteria_domain/models/commission.py
  sale_commission_product_criteria_domain/models/commission_group.py
  sale_commission_product_criteria_domain/models/partner.py
  sale_commission_product_criteria_domain/models/sale_commission_line_mixin.py
  sale_commission_product_criteria_domain/models/sale_order_line_agent.py
Labels: bot is merging ⏳

#536 [16.0][FIX] sale_commission_product_criteria_domain: not agent anymore
  sale_commission_product_criteria_domain/__manifest__.py
  sale_commission_product_criteria_domain/models/account_invoice_line_agent.py
  sale_commission_product_criteria_domain/models/commission.py
  sale_commission_product_criteria_domain/models/commission_group.py
  sale_commission_product_criteria_domain/models/partner.py
  sale_commission_product_criteria_domain/models/sale_commission_line_mixin.py
  sale_commission_product_criteria_domain/models/sale_order_line_agent.py
  sale_commission_product_criteria_domain/static/description/index.html
Labels: bot is merging ⏳

#538 [14.0][FIX] commission credit note
  sale_commission_product_criteria/models/account_move.py
  sale_commission_product_criteria_domain/models/account_invoice_line_agent.py
Labels: approved, bot is merging ⏳
