Repository OCA/commission, pull requests merged in 2024-04, with the labels that each got.

#512 [15.0][FIX] sale_commission: ensure currency
  sale_commission/tests/test_sale_commission.py
Labels: approved, bot is merging ⏳

#513 [16.0][FIX] sale_commission: ensure currency
  sale_commission/tests/test_sale_commission.py
Labels: bot is merging ⏳

#505 [16.0][IMP]account_commission: add test of reversed moves + docs
  account_commission/README.rst
  account_commission/models/commission.py
  account_commission/readme/CONFIGURE.rst
  account_commission/static/description/index.html
  account_commission/tests/test_account_commission.py
Labels: approved, bot is merging ⏳

#507 [16.0][IMP]Place footer outside the table
  account_commission/views/report_settlement_templates.xml
  commission/reports/report_settlement_templates.xml
Labels: approved, ready to merge, bot is merging ⏳

#497 [17.0][MIG] commission: Migration to 17.0
  commission/README.rst
  commission/__init__.py
  commission/__manifest__.py
  commission/data/menuitem_data.xml
  commission/demo/commission_and_agent_demo.xml
  commission/i18n/commission.pot
  commission/i18n/es.po
  commission/i18n/it.po
  commission/i18n/ja.po
  commission/i18n/pt.po
  commission/i18n/pt_BR.po
  commission/models/__init__.py
  commission/models/commission.py
  commission/models/commission_mixin.py
  commission/models/commission_settlement.py
  commission/models/product_template.py
  commission/models/res_partner.py
  commission/pyproject.toml
  commission/readme/CONFIGURE.md
  commission/readme/CONTRIBUTORS.md
  commission/readme/DESCRIPTION.md
  commission/readme/ROADMAP.md
  commission/readme/USAGE.md
  commission/reports/commission_settlement_report.xml
  commission/reports/report_settlement_templates.xml
  commission/security/commission_security.xml
  commission/security/ir.model.access.csv
  commission/static/description/icon.png
  commission/static/description/icon.svg
  commission/static/description/index.html
  commission/tests/__init__.py
  commission/tests/test_commission.py
  commission/views/commission_mixin_views.xml
  commission/views/commission_settlement_views.xml
  commission/views/commission_views.xml
  commission/views/product_template_views.xml
  commission/views/res_partner_views.xml
  commission/wizards/__init__.py
  commission/wizards/commission_make_settle.py
  commission/wizards/commission_make_settle_views.xml
Labels: approved, bot is merging ⏳

#519 [15.0][IMP] commission: Add new settlement period (All pending records) to settle in only one settlement
  account_commission/README.rst
  account_commission/readme/CONTRIBUTORS.rst
  account_commission/static/description/index.html
  account_commission/tests/test_account_commission.py
  commission/README.rst
  commission/models/res_partner.py
  commission/readme/CONTRIBUTORS.rst
  commission/static/description/index.html
  commission/tests/test_commission.py
  commission/wizards/commission_make_settle.py
Labels: approved, bot is merging ⏳
