Repository OCA/commission, pull requests merged in 2024-07, with the labels that each got.

#540 [14.0][IMP] sale_commission_product_criteria_domain: add maintainers
  sale_commission_product_criteria_domain/README.rst
  sale_commission_product_criteria_domain/__manifest__.py
  sale_commission_product_criteria_domain/static/description/index.html
Labels: bot is merging ⏳

#539 [14.0][FIX] sale_commission_geo_assign_product_domain: clear groups
  sale_commission_geo_assign_product_domain/models/res_partner.py
  sale_commission_product_criteria_domain/models/partner.py
Labels: approved, bot is merging ⏳

#517 [MIG] sale_commission_agent_restrict: Migration to 16.0
  sale_commission_agent_restrict/README.rst
  sale_commission_agent_restrict/__init__.py
  sale_commission_agent_restrict/__manifest__.py
  sale_commission_agent_restrict/demo/res_users_demo.xml
  sale_commission_agent_restrict/i18n/es.po
  sale_commission_agent_restrict/i18n/it.po
  sale_commission_agent_restrict/i18n/sale_commission_agent_restrict.pot
  sale_commission_agent_restrict/models/__init__.py
  sale_commission_agent_restrict/models/res_partner.py
  sale_commission_agent_restrict/models/res_users.py
  sale_commission_agent_restrict/models/sale.py
  sale_commission_agent_restrict/models/sale_order_line.py
  sale_commission_agent_restrict/readme/CONFIGURE.rst
  sale_commission_agent_restrict/readme/CONTRIBUTORS.rst
  sale_commission_agent_restrict/readme/DESCRIPTION.rst
  sale_commission_agent_restrict/readme/USAGE.rst
  sale_commission_agent_restrict/security/ir.model.access.csv
  sale_commission_agent_restrict/security/security.xml
  sale_commission_agent_restrict/static/description/icon.png
  sale_commission_agent_restrict/static/description/icon.svg
  sale_commission_agent_restrict/static/description/index.html
  sale_commission_agent_restrict/tests/__init__.py
  sale_commission_agent_restrict/tests/test_sale_commission_agent_restrict.py
  sale_commission_agent_restrict/views/res_partner_views.xml
  sale_commission_agent_restrict/views/sale_order_view.xml
  setup/sale_commission_agent_restrict/odoo/addons/sale_commission_agent_restrict
  setup/sale_commission_agent_restrict/setup.py
Labels: approved, bot is merging ⏳

#534 [MIG] sale_commission_salesman: Migration to 17.0
  sale_commission_salesman/README.rst
  sale_commission_salesman/__init__.py
  sale_commission_salesman/__manifest__.py
  sale_commission_salesman/i18n/ca.po
  sale_commission_salesman/i18n/es.po
  sale_commission_salesman/i18n/es_AR.po
  sale_commission_salesman/i18n/it.po
  sale_commission_salesman/i18n/pt_BR.po
  sale_commission_salesman/i18n/sale_commission_salesman.pot
  sale_commission_salesman/models/__init__.py
  sale_commission_salesman/models/account_move.py
  sale_commission_salesman/models/res_partner.py
  sale_commission_salesman/models/sale_order.py
  sale_commission_salesman/pyproject.toml
  sale_commission_salesman/readme/CONFIGURE.md
  sale_commission_salesman/readme/CONTRIBUTORS.md
  sale_commission_salesman/readme/CREDITS.md
  sale_commission_salesman/readme/DESCRIPTION.md
  sale_commission_salesman/readme/ROADMAP.md
  sale_commission_salesman/readme/USAGE.md
  sale_commission_salesman/static/description/icon.png
  sale_commission_salesman/static/description/icon.svg
  sale_commission_salesman/static/description/index.html
  sale_commission_salesman/tests/__init__.py
  sale_commission_salesman/tests/test_sale_commission_salesman.py
  sale_commission_salesman/views/res_partner_views.xml
Labels: bot is merging ⏳

#542 [14.0][IMP]sale_commission_geo_assign_partner: performance improvement
  sale_commission_geo_assign/wizard/wizard_geo_assign_partner.py
  sale_commission_geo_assign_product_domain/wizards/wizard_geo_assign_partner.py
Labels: approved, bot is merging ⏳

#543 [14.0] [FIX] sale_commission_check_deposit: do not filter non deposited checks
  sale_commission_check_deposit/README.rst
  sale_commission_check_deposit/__manifest__.py
  sale_commission_check_deposit/models/account_journal.py
  sale_commission_check_deposit/readme/DESCRIPTION.rst
  sale_commission_check_deposit/readme/USAGE.rst
  sale_commission_check_deposit/static/description/index.html
  sale_commission_check_deposit/wizard/wizard_check_settle.py
Labels: approved, bot is merging ⏳

#545 [16.0][FIX] sale_commission_product_criteria_domain: clear groups
  sale_commission_product_criteria_domain/models/partner.py
Labels: bot is merging ⏳

#544 [14.0][FIX]sale_commission: settlement report fixes
  sale_commission/README.rst
  sale_commission/static/description/index.html
  sale_commission/views/report_settlement_templates.xml
Labels: approved, ready to merge, bot is merging ⏳

#549 [14.0] [FIX] sale_commission_check_deposit: check date maturity
  sale_commission_check_deposit/wizard/wizard_check_settle.py
Labels: approved, bot is merging ⏳

#548 [14.0][ADD]sale_commission_settlement_report: manage settlement report visualization
  sale_commission_settlement_report/README.rst
  sale_commission_settlement_report/__init__.py
  sale_commission_settlement_report/__manifest__.py
  sale_commission_settlement_report/models/__init__.py
  sale_commission_settlement_report/models/res_company.py
  sale_commission_settlement_report/models/res_config_settings.py
  sale_commission_settlement_report/models/sale_commission_settlement.py
  sale_commission_settlement_report/models/sale_commission_settlement_line.py
  sale_commission_settlement_report/readme/CONFIGURE.rst
  sale_commission_settlement_report/readme/DESCRIPTION.rst
  sale_commission_settlement_report/static/description/index.html
  sale_commission_settlement_report/views/report_settlement_templates.xml
  sale_commission_settlement_report/views/res_config_settings_view.xml
  sale_commission_settlement_report/views/sale_commission_settlement_view.xml
  setup/sale_commission_settlement_report/odoo/addons/sale_commission_settlement_report
  setup/sale_commission_settlement_report/setup.py
Labels: approved, bot is merging ⏳

#550 [14.0] [FIX] sale_commission_partial_settlement: reset agent partial
  sale_commission_partial_settlement/README.rst
  sale_commission_partial_settlement/__manifest__.py
  sale_commission_partial_settlement/migrations/14.0.1.0.1/post-migrate.py
  sale_commission_partial_settlement/models/account_move.py
  sale_commission_partial_settlement/static/description/index.html
Labels: approved, bot is merging ⏳
