Repository OCA/commission, pull requests merged in 2025-03, with the labels that each got.

#595 [MIG] sale_commission_pricelist: Migration to 17.0
  sale_commission_pricelist/README.rst
  sale_commission_pricelist/__init__.py
  sale_commission_pricelist/__manifest__.py
  sale_commission_pricelist/i18n/de.po
  sale_commission_pricelist/i18n/es.po
  sale_commission_pricelist/i18n/es_AR.po
  sale_commission_pricelist/i18n/fr.po
  sale_commission_pricelist/i18n/it.po
  sale_commission_pricelist/i18n/pt.po
  sale_commission_pricelist/i18n/pt_BR.po
  sale_commission_pricelist/i18n/sale_commission_pricelist.pot
  sale_commission_pricelist/i18n/tr.po
  sale_commission_pricelist/i18n/zh_CN.po
  sale_commission_pricelist/models/__init__.py
  sale_commission_pricelist/models/product_pricelist.py
  sale_commission_pricelist/models/sale_order_line.py
  sale_commission_pricelist/models/sale_order_line_agent.py
  sale_commission_pricelist/pyproject.toml
  sale_commission_pricelist/readme/CONTRIBUTORS.md
  sale_commission_pricelist/readme/DESCRIPTION.md
  sale_commission_pricelist/readme/USAGE.md
  sale_commission_pricelist/static/description/icon.png
  sale_commission_pricelist/static/description/icon.svg
  sale_commission_pricelist/static/description/index.html
  sale_commission_pricelist/tests/__init__.py
  sale_commission_pricelist/tests/test_sale_commission_pricelist.py
  sale_commission_pricelist/views/product_pricelist_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#600 [15.0][OU] commission: Precompute can_edit
  commission/migrations/15.0.2.0.0/pre-migration.py
Labels: approved

#607 [14.0][FIX] sale_commission: pay commissions on reversed invoices
  sale_commission/README.rst
  sale_commission/models/account_move.py
  sale_commission/models/sale_commission.py
  sale_commission/readme/CONFIGURE.rst
  sale_commission/static/description/index.html
  sale_commission/tests/test_sale_commission.py
Labels: approved, bot is merging ⏳
