Repository OCA/commission, pull requests merged in 2025-01, with the labels that each got.

#559 [MIG] hr_commission: Migration to 14.0
  hr_commission/README.rst
  hr_commission/__init__.py
  hr_commission/__manifest__.py
  hr_commission/i18n/ca.po
  hr_commission/i18n/ca_ES.po
  hr_commission/i18n/es.po
  hr_commission/i18n/hr_commission.pot
  hr_commission/i18n/pt_BR.po
  hr_commission/models/__init__.py
  hr_commission/models/hr_employee.py
  hr_commission/models/res_partner.py
  hr_commission/models/sale_commission_settlement.py
  hr_commission/readme/CONTRIBUTORS.rst
  hr_commission/readme/DESCRIPTION.rst
  hr_commission/readme/ROADMAP.rst
  hr_commission/static/description/icon.png
  hr_commission/static/description/icon.svg
  hr_commission/static/description/index.html
  hr_commission/tests/__init__.py
  hr_commission/tests/test_hr_commission.py
  hr_commission/views/res_partner_view.xml
  hr_commission/views/sale_commission_settlement_views.xml
  setup/hr_commission/odoo/addons/hr_commission
  setup/hr_commission/setup.py
Labels: approved, bot is merging ⏳, stale

#586 [14.0][FIX] sale_commission_partial_settlement: major refactor
  sale_commission_partial_settlement/README.rst
  sale_commission_partial_settlement/__manifest__.py
  sale_commission_partial_settlement/migrations/14.0.1.2.1/post-migrate.py
  sale_commission_partial_settlement/migrations/14.0.2.0.0/post-migrate.py
  sale_commission_partial_settlement/models/__init__.py
  sale_commission_partial_settlement/models/account_invoice_line_agent.py
  sale_commission_partial_settlement/models/account_invoice_line_agent_partial.py
  sale_commission_partial_settlement/models/account_partial_reconcile.py
  sale_commission_partial_settlement/models/sale_commission_settlement.py
  sale_commission_partial_settlement/models/sale_commission_settlement_line.py
  sale_commission_partial_settlement/models/sale_commission_settlement_line_partial.py
  sale_commission_partial_settlement/readme/ROADMAP.rst
  sale_commission_partial_settlement/security/ir.model.access.csv
  sale_commission_partial_settlement/static/description/index.html
  sale_commission_partial_settlement/tests/test_partial_settlement.py
  sale_commission_partial_settlement/views/account_invoice_line_agent_partial_views.xml
  sale_commission_partial_settlement/views/account_invoice_line_agent_views.xml
  sale_commission_partial_settlement/views/sale_commission_settlement_line_partial_views.xml
  sale_commission_partial_settlement/wizard/wizard_settle.py
Labels: approved, bot is merging ⏳

#592 [14.0][FIX] sale_commission_partial_settlement: no more flaky test
  sale_commission_partial_settlement/tests/test_partial_settlement.py
Labels: bot is merging ⏳
