Repository OCA/commission, pull requests merged in 2025-04, with the labels that each got.

#609 [16.0][IMP] comission: Fix product view
  commission/views/product_template_views.xml
Labels: bot is merging ⏳

#610 [18.0][MIG] commission + rename to commission_oca
  commission_oca/README.rst
  commission_oca/__init__.py
  commission_oca/__manifest__.py
  commission_oca/data/menuitem_data.xml
  commission_oca/demo/commission_and_agent_demo.xml
  commission_oca/i18n/commission_oca.pot
  commission_oca/i18n/es.po
  commission_oca/i18n/it.po
  commission_oca/i18n/ja.po
  commission_oca/i18n/pt.po
  commission_oca/i18n/pt_BR.po
  commission_oca/i18n/tr.po
  commission_oca/models/__init__.py
  commission_oca/models/commission.py
  commission_oca/models/commission_mixin.py
  commission_oca/models/commission_settlement.py
  commission_oca/models/product_template.py
  commission_oca/models/res_partner.py
  commission_oca/pyproject.toml
  commission_oca/readme/CONFIGURE.md
  commission_oca/readme/CONTRIBUTORS.md
  commission_oca/readme/DESCRIPTION.md
  commission_oca/readme/ROADMAP.md
  commission_oca/readme/USAGE.md
  commission_oca/reports/commission_settlement_report.xml
  commission_oca/reports/report_settlement_templates.xml
  commission_oca/security/commission_security.xml
  commission_oca/security/ir.model.access.csv
  commission_oca/static/description/icon.png
  commission_oca/static/description/icon.svg
  commission_oca/static/description/index.html
  commission_oca/tests/__init__.py
  commission_oca/tests/test_commission.py
  commission_oca/views/commission_mixin_views.xml
  commission_oca/views/commission_settlement_views.xml
  commission_oca/views/commission_views.xml
  commission_oca/views/product_template_views.xml
  commission_oca/views/res_partner_views.xml
  commission_oca/wizards/__init__.py
  commission_oca/wizards/commission_make_settle.py
  commission_oca/wizards/commission_make_settle_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#611 [18.0][MIG] account_commission + rename to account_commission_oca
  account_commission_oca/README.rst
  account_commission_oca/__init__.py
  account_commission_oca/__manifest__.py
  account_commission_oca/data/menuitem_data.xml
  account_commission_oca/i18n/account_commission_oca.pot
  account_commission_oca/i18n/es.po
  account_commission_oca/i18n/hr.po
  account_commission_oca/i18n/it.po
  account_commission_oca/i18n/ja.po
  account_commission_oca/i18n/pt.po
  account_commission_oca/i18n/pt_BR.po
  account_commission_oca/i18n/tr.po
  account_commission_oca/models/__init__.py
  account_commission_oca/models/account_move.py
  account_commission_oca/models/commission.py
  account_commission_oca/models/commission_settlement.py
  account_commission_oca/pyproject.toml
  account_commission_oca/readme/CONFIGURE.md
  account_commission_oca/readme/CONTRIBUTORS.md
  account_commission_oca/readme/DESCRIPTION.md
  account_commission_oca/readme/USAGE.md
  account_commission_oca/report/__init__.py
  account_commission_oca/report/commission_analysis.py
  account_commission_oca/report/commission_analysis_view.xml
  account_commission_oca/security/account_commission_security.xml
  account_commission_oca/security/ir.model.access.csv
  account_commission_oca/static/description/icon.png
  account_commission_oca/static/description/icon.svg
  account_commission_oca/static/description/index.html
  account_commission_oca/tests/__init__.py
  account_commission_oca/tests/test_account_commission.py
  account_commission_oca/views/account_move_views.xml
  account_commission_oca/views/commission_settlement_views.xml
  account_commission_oca/views/commission_views.xml
  account_commission_oca/views/report_settlement_templates.xml
  account_commission_oca/wizards/__init__.py
  account_commission_oca/wizards/commission_make_settle.py
  account_commission_oca/wizards/wizard_invoice.py
  account_commission_oca/wizards/wizard_invoice.xml
  commission_oca/models/commission_mixin.py
Labels: approved, bot is merging ⏳
