Repository OCA/commission, pull requests merged in 2025-05, with the labels that each got.

#612 [18.0][MIG] sale_commission + rename to sale_commission_oca
  sale_commission_oca/README.rst
  sale_commission_oca/__init__.py
  sale_commission_oca/__manifest__.py
  sale_commission_oca/i18n/es.po
  sale_commission_oca/i18n/it.po
  sale_commission_oca/i18n/ja.po
  sale_commission_oca/i18n/pt_BR.po
  sale_commission_oca/i18n/sale_commission_oca.pot
  sale_commission_oca/i18n/tr.po
  sale_commission_oca/models/__init__.py
  sale_commission_oca/models/sale_order.py
  sale_commission_oca/pyproject.toml
  sale_commission_oca/readme/CONTRIBUTORS.md
  sale_commission_oca/readme/DESCRIPTION.md
  sale_commission_oca/readme/USAGE.md
  sale_commission_oca/security/ir.model.access.csv
  sale_commission_oca/static/description/icon.png
  sale_commission_oca/static/description/icon.svg
  sale_commission_oca/static/description/index.html
  sale_commission_oca/tests/__init__.py
  sale_commission_oca/tests/test_sale_commission.py
  sale_commission_oca/views/sale_order_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#614 [18.0][FIX] commission_oca: fix web icon path
  commission_oca/data/menuitem_data.xml
Labels: bot is merging ⏳

#620 [14.0][FIX] sale_commission_queued: add missing file to manifest data
  sale_commission_queued/__manifest__.py
Labels: approved, bot is merging ⏳

#615 [16.0] [REF] sale_commission_product_criteria: refactor sql query to be inheritable
  sale_commission_product_criteria/models/sale_commission_line_mixin.py
Labels: approved, ready to merge, bot is merging ⏳
